
spring.datasource.url=jdbc:postgresql://localhost:5432/booknest-dev


spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=465
spring.mail.username=baf265f7cffa71
spring.mail.domain=@mailtrap.io
spring.mail.password=7230abc9fdb68a
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

logging.level.org.springframework.mail=DEBUG
# Enable debug logging for the underlying JavaMail/Jakarta Mail sender
://level.com.sun.mail.smtp=DEBUG
spring.mail.properties.mail.debug=false

