
spring.datasource.url=${DEV_DATABASE}


spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=465
spring.mail.username=${MAILTRAP_USERNAME}
spring.mail.domain=@mailtrap.io
spring.mail.password=${MAILTRAP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

logging.level.org.springframework.mail=DEBUG
# Enable debug logging for the underlying JavaMail/Jakarta Mail sender
://level.com.sun.mail.smtp=DEBUG
spring.mail.properties.mail.debug=false

